import env from "../lib/env/index.mjs";

export const BUSINESS_VISA_APPLICANTS_BASE_ID =
    env.AIRTABLE_BUSINESS_VISA_APPLICANTS_BASE_ID;
export const BUSINESS_VISA_APPLICANTS_PROJECT_ID =
    env.AIRTABLE_BUSINESS_VISA_APPLICANTS_PROJECT_ID;
